language: node_js
node_js:
  - "11"

cache: npm

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/caffeine-vue

before_install:
  - npm install -g @vue/cli

install:
  - npm ci

script:
  - npx vue-cli-service lint --no-fix
  - npx vue-cli-service test:unit

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "jiXGqD9X8dOStzIdghToRg/4V+rPBl9vzAHr6fuqNq12fTyEWbyobjTQB1aADH4SGtqcDzy7c10P81WblYfl0dpZy4JWIsDmTuyouByDIwRNY4aNyXbfAMIVhv8ek65IbaFfYc9VOF5V/63IxyqS16J0D/zHk6wbuQ5pVH6JiDBurxEuca4U94eeeiOwHw4Y/qPUGaFs5ASJorokhEIggFvCoUc/Cg56SoY8Z7MnG+OZghENFSxxSIZH4lzE3NgOJomo8NuhK4k6ELkYgabkosRAMId8fWpZJWh8YzbbnxItiiK+FT+FSALsRuNJ2g0buV1RWFuiwTnnFely8lYmREg5vEYggchogeBXX1YHBit4Vk2JEIRwPzyO4w06L6Ff7KiuGmnm33RGIjIFnzklB04j/11wNkojwvDdFeG3S/2CkyBNDOZ5LXm/PH/OrHBvdhUTI8tVbNB2yAajIOq582gzgP4mwSvCbO3pmPRKM9ggWHbOTs0TnBL0hJBpXj7XJ1GVWRzFvvGAsbcBBTvMkyGwEnTBqlEefWxYVRdO353GsChY31Bh8pJC+xWjrkAY/sXvCiKZLyZvVZFuBa5oYAgOGaqsMszWX5SJ5sYjf5ohedQklkAoZWs01MY7nPqKm0dnAJFoGIJ7c4ZeXtcfypAJemk7ktpYi/h818BVYZM="
    on_success: change
    on_failure: change
    on_pull_requests: false
