<template>
  <div>
    <v-container>
      <v-layout column align-center>
        <v-flex md6>
          <h1>Privacy Policy</h1>
          <p>
            Your privacy is important to us. It is DD-DeCaF Consortium's policy
            to respect your privacy regarding any information we may collect
            from you across our website,
            <a href="http://caffeine.dd-decaf.eu">
              http://caffeine.dd-decaf.eu</a
            >, and other sites we own and operate.
          </p>
          <p>
            We only ask for personal information when we truly need it to
            provide a service to you. We collect it by fair and lawful means,
            with your knowledge and consent. We also let you know why we’re
            collecting it and how it will be used.
          </p>
          <p>
            We only retain collected information for as long as necessary to
            provide you with your requested service. What data we store, we’ll
            protect within commercially acceptable means to prevent loss and
            theft, as well as unauthorised access, disclosure, copying, use or
            modification.
          </p>
          <p>
            We don’t share any personally identifying information publicly or
            with third-parties, except when required to by law.
          </p>
          <p>
            Our website may link to external sites that are not operated by us.
            Please be aware that we have no control over the content and
            practices of these sites, and cannot accept responsibility or
            liability for their respective privacy policies.
          </p>
          <p>
            You are free to refuse our request for your personal information,
            with the understanding that we may be unable to provide you with
            some of your desired services.
          </p>
          <p>
            Your continued use of our website will be regarded as acceptance of
            our practices around privacy and personal information. If you have
            any questions about how we handle user data and personal
            information, feel free to contact us.
          </p>
          <p>This policy is effective as of 10 May 2019.</p>
          <!-- <p>
            Generated by
            <a
              title="Privacy Policy Template Generator"
              href="https://getterms.io/"
              >GetTerms.io</a
            >
          </p> -->
        </v-flex>
        <v-flex>
          <v-btn color="primary" class="mb-3" @click="switchVisibility()"
            >Change Privacy Settings</v-btn
          >
        </v-flex>
        <v-flex md6 v-if="showForm">
          <v-layout column align-center>
            <v-form>
              <v-flex
                v-for="option in this.$store.state.session.cookieOptions"
                :key="option.category"
              >
                <v-checkbox
                  :label="option.label"
                  color="primary"
                  v-model="cookies[option.category]"
                  :messages="option.message"
                  :disabled="!option.canOptOut"
                ></v-checkbox>
              </v-flex>
            </v-form>
            <v-btn color="primary" class="mb-3" @click="acceptPrivacyChanges()"
              >Save Changes</v-btn
            >
          </v-layout>
        </v-flex>
      </v-layout>
    </v-container>
    <v-snackbar
      color="success"
      v-model="isSettingsChangeSuccess"
      :timeout="6000"
    >
      Updated cookie settings successfully!
    </v-snackbar>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Consent, CookieOption } from "@/store/modules/session";

export default Vue.extend({
  name: "PrivacyPolicy",
  data: () => ({
    showForm: false,
    cookies: {
      strictlyNecessary: false,
      preferences: false,
      statistics: false,
      marketing: false
    },
    isSettingsChangeSuccess: false
  }),
  created() {
    this.$store.state.session.cookieOptions.forEach((option: CookieOption) => {
      this.cookies[option.category] = option.default;
    });
    this.$store.state.session.consentsPromise.then(() => {
      this.$store.state.session.consents
        .filter(({ category }: Consent) => category !== "strictly_necessary")
        .forEach((consent: Consent) => {
          if (this.cookies.hasOwnProperty(consent.category)) {
            this.cookies[consent.category] = this.$store.getters[
              "session/isConsentAccepted"
            ](consent);
          }
        });
    });
  },
  methods: {
    switchVisibility() {
      this.showForm = this.showForm ? false : true;
    },
    acceptPrivacyChanges() {
      this.$store.state.session.cookieOptions.forEach(
        ({ category, message }: CookieOption) => {
          this.$store.dispatch("session/addCookieConsent", {
            category: category,
            message: message,
            status: this.cookies[category] ? "accepted" : "rejected",
            source: "cookie_consent_banner"
          });
        }
      );
      this.isSettingsChangeSuccess = true;
    }
  }
});
</script>
